---
title: Appendix The Public Service Motivation Construct and Scale
author: Isaiah Espinoza
---

# Appendix: The Public Service Motivation Construct and Scale

The following is a brief overview of the Public Service Motivation scale and construct as developed by @perry1996. Perry defines Public Service Motivation (PSM), "as an individual's predisposition to respond to motives grounded primarily or uniquely in public institutions" [-@perry1996, 6]. An interesting aspect of the PSM construct and scale is that it is predicated on a particular understanding of motivation rooted in evolutionary psychology, and is also found elsewhere in social psychology literature [For review, see @higgins2021, 88]. Here and in other related work, motives are driven by needs. In particular, certain "drive theories" of motivation suggest that humans recognize something as a 'need' when its deprivation threatens our survival, our growth, or our ultimate life satisfaction and well-being. The motivation to fulfill unmet 'needs' may guide our behavior, impact on our thoughts, explain our selective attention and memory [@gardner2000; @hull1943; @mcleod2022]. As it relates to PSM, @perry1996 recognized three analytically distinct motivational categories: rational, norm-based, and affective.

> "Rational motives involve actions grounded in individual utility maximization. Norm-based motives refer to actions generated by efforts to conform to norms. Affective motives refer to those triggers of behavior that are grounded in emotional responses to various social contexts." [@perry1996, 6]

The PSM scale development was based on conceptual dimensions which were categorized into the motivational categories. The final PSM scale was confirmed as having four component dimensions: attraction to public policy making, commitment to the public interest, compassion, and self-sacrifice. However, the initial analysis of the finalized PSM scale demonstrated no distinct difference in model fit between a three and four dimensional PSM model. The public interest and self-sacrifice component dimensions were highly correlated, and so a comparison between the three and four-dimensional model was done. The four dimensional model showed a slighter higher $𝛘^2$ statistic, thus @perry1996 opted to retain the self-sacrifice dimension to maintain the four dimensional model of the PSM scale because, "it has had a historical connection to how we think about public service that is explicitly preserved by retaining the dimension." [@perry1996, 20]. However, it is recommended by Perry that further refinements to the PSM construct and scale be undertaken by future research.

The four component dimensions of the Public Service Motivation scale are described below;

Attraction to public policy making (rational motive)

:   Refers to a rational motive in which the opportunity to participation in the formation of public policy draws individuals to public service

Commitment to the public interest (norm-based)

:   An altruistic desire to serve the public interest

Compassion (aka "patriotism of benevolence", affective)

:   An affective state that combines the love of regime values and the love of others which drives people to exemplify "a patriotism of benevolence"[^22]

Self-sacrifice (unclear motive)

:   Refers to the willingness to substitute service to others for tangible personal rewards. In other words, the willingness of public servants to forego financial rewards for the intangible rewards received from serving the public.

After refinements were made to the initial scale, the resulting Public Service Motivation Scale was finalized to include 24-items measuring four component dimensions. The PSM measurement items are measured with Likert type response options. The items are listed in the table below

+-------------------+----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Motive type       | Component Dimension                          | Item Wording                                                                                                                   |
+===================+==============================================+================================================================================================================================+
| Rational Motive   | Public Policy Making                         | -   PSM 11 Politics is a dirty word. (Reversed)                                                                                |
|                   |                                              | -   PSM 27 The give and take of public policy making doesn't appeal to me. (Reversed)                                          |
|                   |                                              | -   PSM 31 I don't care much for politicians. (Reversed)                                                                       |
+-------------------+----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Norm-based motive | Public Interest                              | -   PSM 16 It is hard for me to get intensely interested in what is going on in my community. (Reversed)                       |
|                   |                                              | -   PSM 23 I unselfishly contribute to my community.                                                                           |
|                   |                                              | -   PSM 30 Meaningful public service is very important to me.                                                                  |
|                   |                                              | -   PSM 34 I would prefer seeing public officials do what is best for the whole community even if it harmed my interests.      |
|                   |                                              | -   PSM 39 I consider public service my civic duty.                                                                            |
+-------------------+----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Affective motive  | Compassion (aka "patriotism of benevolence") | -   PSM 2 I am rarely moved by the plight of the underprivileged. (Reversed)                                                   |
|                   |                                              | -   PSM 3 Most social programs are too vital to do without.                                                                    |
|                   |                                              | -   PSM 4 It is difficult for me to contain my feelings when I see people in distress.                                         |
|                   |                                              | -   PSM 8 To me, patriotism includes seeing to the welfare of others.                                                          |
|                   |                                              | -   PSM 10 I seldom think about the welfare of people whom I don't know personally. (Reversed)                                 |
|                   |                                              | -   PSM 13 I am often reminded by daily events about how dependent we are on one another.                                      |
|                   |                                              | -   PSM 24 I have little compassion for people in need who are unwilling to take the first step to help themselves. (Reversed) |
|                   |                                              | -   PSM 40 There are few public programs that I wholeheartedly support. (Reversed)                                             |
+-------------------+----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Unclear           | Self-sacrifice                               | -   PSM 1 Making a difference in society means more to me than personal achievements.                                          |
|                   |                                              |                                                                                                                                |
|                   |                                              | -   PSM 5 I believe in putting duty before self.                                                                               |
|                   |                                              |                                                                                                                                |
|                   |                                              | -   PSM 6 Doing well financially is definitely more important to me than doing good deeds. (Reversed)                          |
|                   |                                              |                                                                                                                                |
|                   |                                              | -   PSM 9 Much of what I do is for a cause bigger than myself.                                                                 |
|                   |                                              |                                                                                                                                |
|                   |                                              | -   PSM 12 Serving citizens would give me a good feeling even if no one paid me for it.                                        |
|                   |                                              |                                                                                                                                |
|                   |                                              | -   PSM 17 I feel people should give back to society more than they get from it.                                               |
|                   |                                              |                                                                                                                                |
|                   |                                              | -   PSM 19 I am one of those rare people who would risk personal loss to help someone else.                                    |
|                   |                                              |                                                                                                                                |
|                   |                                              | -   PSM 26 I am prepared to make enormous sacrifices for the good of society.                                                  |
+-------------------+----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+

: Public Service Motivation Scale Item Wording [@perry1996]


