---
title: "Appendix: Methodological Notes and Critiques Related to Literature on Psychological Empowerment"
author:  Isaiah Espinoza
---

## On the Measurement of Psychological Empowerment: Reivew Speicifc to @spreitzer1995

As stated in the main text, the Psychological Empowerment scale measurement instrument includes 12-items with the component dimensions measured with three items each. In this case, psychological empowerment is understood as a common second-order latent factor that underlies the four latent component factors (e.g., meaning, impact, competence, self-determination). Initial analysis of the measurement scale revealed significant correlation between the component factors, suggesting a lack of discriminant validity between the four dimensional components of empowerment. Further research should be done to further refine the theory and measurement of psychological empowerment [@spreitzer1995, 1458].

Validity and reliability was assessed for the four components of empowerment by examination of the overall Cronbach's alpha ($\alpha$) of the scale and the same was done for each component as well. The measurement scales for the four components of empowerment were found to be valid and moderately reliable. Second-order confirmatory factor analysis (CFA) was used to assess the convergent and discriminant validity of the empowerment measures in both samples. Second-order confirmatory factor analysis is structurally equivalent to first-order CFA: there is an unobservable latent factor (i.e., construct) theorized to be influential upon observable referents, or indicators. For second-order CFA, the latent factor is theorized to be a common higher level factor influential upon a set of other lower level latent component factors.

It's important to make a quick note on the survey sample and data collection strategy used in this study to develop and validate the measurement scale of psychological empowerment. Especially since this scale is referenced and drawn upon often in subsequent research. Survey data was collected for two distinct samples of a Fortune 50 industrial company. The first sample ($n = 393$) comprised of managers from across departments. Manager respondents were surveyed over a period of three years until a 100% response rate was achieved (this was not panel data). This first primary sample consisted of mid-level managers, $93\%$ male, $85\%$ White, average age of $46$ years, an average tenure of $13$ years at the company, and average time in position of $3$ years. The extent that this sample is representative of people with jobs, generally speaking, is probably pretty low. But more importantly, the author was trying to develop and validate a novel measure of empowerment by testing it on a sample that is likely to be more empowered than the average worker. It is not clear why the sample was confined to this group, but it seems like it would have made more sense to randomly sample all employees.

In contrast, the second sample was surveyed at two different intervals spanning five months in between survey administration, and consisted of (non-managerial) employees ($n = 128$) of the same company. The author reported a difference in measurement validity between the two samples; the Cronbach's alpha for the overall measure of empowerment was $\alpha = 0.72$ for the primary industrial sample of managers, but $\alpha = 0.62$ for the second sample of employees. This calls into question whether the equivalence assumption [@pietryka2022] holds for this measurement scale. Additionally, the primary sample of managers were surveyed across a period of three years at the beginning of a managerial development program. Seeing as how these managers all work in the same company, it apparently wasn't considered that any of the managers of the sample would talk to each other about the survey over the period of three years, which potentially may have contaminated the results of the study.

Using the new measure for psychological empowerment, @spreitzer1995 tested whether the scale significantly predicted two outcomes: managerial effectiveness and innovative behavior. The former was defined as, "the degree to which a manager fulfills or exceeds work role expectations" [-@spreitzer1995, 1448]. Note that "managerial effectiveness" does not only pertain to workers who are employed as managers, but rather apparently refers to a kind of effectiveness which would be described as "managerial". Spreitzer explains, "Because, by definition, empowered managers see themselves as competent and able to influence their jobs and work environments in meaningful ways, they are likely to proactively execute their job responsibilities by, for instance, anticipating problems and acting independently, and hence are likely to be seen as effective." [-@spreitzer1995, 1448]. Innovative behavior was defined as "the creation of something new or different". 

It is unclear what survey items were used to measure these two behavioral outcomes, but both managerial effectiveness and innovative behavior was ascertained by questioning the subordinate employees of the managers from the primary sample. The two behavioral outcomes were found to be significantly related to empowerment, but the marginal fit of the model was said to be likely due to multicollinearity between those two behavioral outcomes.

Spreitzer also fit a Multiple Indicators Multiple Causes (MIMIC) model to test whether certain factors were antecedent to empowerment. This attempt to identify individual and contextual factors antecedent to empowerment found partial support, but was not substantially convincing. Many of the independent constructs theorized to influence empowerment overlap in definition or description and are not independent in that they potentially cause or influence each other. Each factor is nevertheless theorized to have independent influence on empowerment. For example, feedback (i.e., information about performance) and self-esteem are considered as two independent factors that are antecedent to empowerment. The former contextual, the latter a dispositional trait. However, feedback on performance likely impacts self-esteem despite its conception as a stable and enduring disposition. That raises issues of endogeneity (two independent variables not so independent).


## Psychological Empowerment as a Mediator: Review Specific to @liden2000 and @shapira-lishchinsky2014

As stated in the main text, two of the three studies examining psychological empowerment as a mediating variable appeared problematic upon review. What follows are my initial impressions and critiques upon review of @liden2000 and @shapira-lishchinsky2014. 

The earliest of these studies shows that the meaning and competence dimensions of psychological empowerment have significant influence on organizational commitment [@liden2000]. However, the cited study appears somewhat questionable in terms of method and measurement of the relevant variables. The cited study uses the term "mediator variables" to describe the empowerment component dimensions, but the analysis conducted appears to have consisted of multivariate OLS. The dependent variables were workplace satisfaction, organizational commitment, and job performance, whereas the independent variables included every component of empowerment, leadership-member exchange (relationship with leadership) and team-member exchange (relationship with coworkers), and job characteristics. 

The authors present three OLS models, with the last multivariate OLS model being the most significant as it includes both the "mediator variables" (empowerment components) and other independent variables all together. Looking at this Table 4 [@liden2000, 413], the only statistically significant positively related independent variables to work satisfaction are job characteristics and the meaning component of empowerment, whereas competence shows a significant negative influence on work satisfaction--on average and holding all else equal. This finding in Table 4 suggests that an increase in feelings of competence in one's job decreases work satisfaction. In addition, The measurement for work satisfaction was measured by marking "yes" for adjectives connotating satisfaction, but responses are coded so that a "yes" = 3, whereas a "no" = 0. This coding scheme would seemingly inflate the Cronbach's alpha for the measure of work satisfaction and doesn't convey convincing construct nor face validity. The measurement of the relevant variables (save for the empowerment components) and the analysis of the study makes the reported findings in @liden2000 article appear dubious.

A relatively more recent study examined whether psychological empowerment serves as a mediating variable between teachers perceptions of authentic leadership and OCB and withdraw behaviors (e.g., lateness and voluntary absence frequency) [@shapira-lishchinsky2014]. The essential findings of the research intuitively suggest that when the boss is perceived as an 'authentic leader', employees (teachers) are increasingly motivated to perform above and beyond what is required of them and report no intent to leave their current job. Here, issues arise in the description and measurement of psychological empowerment, which somewhat undermine the reported findings. The cited authors employ a selective approach to the use of different measurement scales, and when it came to psychological empowerment, chose to reduce the component dimensions down to two and selected eight of the original 12 survey items. 

The confirmatory factor analysis conducted by @shapira-lishchinsky2014 yielded two factors but the method is literally an analysis meant to confirm the number of expected factors previously theorized. The authors operationally conceived of psychological empowerment as a two dimensional construct. The authors limited the number of factors down to two, selected 8 out of 12 items from the original psychological empowerment scale, and then conducted an analysis to confirm that survey data sufficiently loads onto only two factors. The thing is, the original psychological empowerment scale is comprised of four latent factors derived from 12-items, where 3 items are used to measure each component factor. The original conception of psychological empowerment has four (latent) dimensions. Seeing as how the analysis by @spreitzer1995 found that divergent validity was lacking among the component factors, the selective use of various survey items from the original scale is likely to only exacerbate such issues of scale validity.

\newpage

# References